Repository FRONTENDBOOTCAMP-11th/DAEDDA, pull requests merged in 2024-12, with the labels that each got.

#13 📝 docs: test 리드미 추가
  test.md
Labels: low

#25 [FEAT] Button 공통 컴포넌트 제작
  src/components/layout/Button.jsx
Labels: enhancement, high

#24 [FEAT] 인풋 컴포넌트 사용
  src/components/layout/InputField.jsx
  src/pages/main/MainList.jsx
Labels: enhancement, high

#32 [FEAT] 헤더와 푸터 100vh 화면에 고정
  public/icons/footer/footerStar.svg
  public/icons/footer/heart.svg
  public/icons/footer/history.svg
  public/icons/footer/purpleHeart.svg
  public/icons/footer/purpleHistory.svg
  public/icons/footer/purpleStar.svg
  src/App.jsx
  src/components/layout/Footer.jsx
  src/components/layout/MainHeader.jsx
  src/components/layout/index.jsx
  src/pages/main/MainList.jsx
Labels: enhancement, high

#40 [FEAT] TitleHeader 페이지별 title 반영
  src/components/layout/Header.jsx
Labels: high

#27 [FEAT] main 리스트 페이지 추가
  src/assets/images/main-sample.png
  src/pages/main/MainList.jsx
Labels: enhancement, high

#47 [FEAT]myPage 마크업 완료
  public/icons/.gitkeep
  public/icons/arrow.svg
  public/icons/badge.svg
  public/icons/customerSupport.svg
  public/icons/energyBar.svg
  public/icons/energyBar2.svg
  public/icons/heart.svg
  public/icons/opnion.svg
  public/icons/power.svg
  public/icons/review.svg
  public/icons/terms.svg
  public/icons/userInfo.svg
  public/images/crying_daeddamon.png
  public/images/logo.png
  public/images/logo_title.png
  public/images/smiling_daeddamon.png
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageList.jsx
Labels: enhancement, high

#50 [FEAT] 로그인 페이지 마크업 완성
  .gitignore
  src/pages/user/SignIn.jsx
Labels: enhancement, high

#29 [FEAT] 약관 페이지 마크업 완성
  src/pages/user/Terms.jsx
Labels: enhancement, high

#51 [FEAT] 회원가입 페이지 완성
  src/pages/user/SignUp.jsx
Labels: enhancement, high

#42 [FEAT] 리뷰 페이지 UI 작업 (알바 내역 페이지)
  src/pages/reviews/MyPerson.jsx
  src/pages/reviews/MyPlace.jsx
  src/pages/reviews/ReviewList.jsx
Labels: enhancement, high

#44 [FEAT] 리뷰 작성 페이지 UI 작업
  public/icons/reviews/blankStar.svg
  src/pages/reviews/ReviewWrite.jsx
Labels: enhancement, high

#49 [FEAT] 관심 리스트 페이지 마크업 완료
  public/icons/apply.svg
  public/icons/likes.svg
  src/pages/myPage/Likes.jsx
Labels: enhancement, high

#15 [FEAT] main 글쓰기 페이지 마크업 추가 및 부 타이틀 제목 추가
  routes.jsx
  src/components/layout/Button.jsx
  src/components/layout/InputField.jsx
  src/index.css
  src/pages/main/MainWrite.jsx
  src/pages/mainWrite/Write.jsx
Labels: high

#52 [FEAT] 공고 PR 상세 페이지 UI 작업 완료
  src/pages/pr/PRDetail.jsx
Labels: high

#53 [FEAT] main 상세 페이지 UI 완성
  routes.jsx
  src/components/layout/InputField.jsx
  src/pages/main/MainDetail.jsx
  src/pages/main/MainList.jsx
Labels: enhancement, high

#54 [FEAT] PR 입력 페이지 UI
  routes.jsx
  src/pages/main/MainList.jsx
  src/pages/pr/PRWrite.jsx
Labels: enhancement, high

#56 [FEAT] PREdit 수정 페이지 UI 추가
  src/pages/pr/PREdit.jsx
Labels: enhancement, high

#59 [FEAT] main 공고 수정 페이지 UI 추가
  src/pages/main/MainEdit.jsx
Labels: enhancement, high

#57 [FEAT] 내가 받은 리뷰 보기 페이지 마크업 완성
  src/pages/myPage/MyReviews.jsx
Labels: enhancement, high

#48 [FEAT] 회원 정보 수정 마크업 완료
  public/icons/imgEdit.svg
  src/pages/myPage/Edit.jsx
Labels: enhancement, high

#69 [FEAT] 메인 리스트 페이지 UI 작업 (reopen)
  public/icons/whitePlus.svg
  src/pages/main/MainList.jsx
Labels: enhancement, high

#67 [FEAT] user 페이지 수정
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: enhancement, high

#70 [FEAT] 프로필 페이지 UI 작업 완료
  public/icons/imgEdit.svg
  public/icons/write.svg
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageList.jsx
  src/pages/user/Profile.jsx
Labels: enhancement, high

#72 [FEAT] myPage의 className custom
  src/index.css
  src/pages/myPage/Likes.jsx
  src/pages/myPage/MyReviews.jsx
Labels: enhancement, high

#77 [FEAT] 메인 상세 페이지 유저 프로필에 알바력 디자인 변경, 버튼 위치 변경, 아이콘 추가
  public/icons/blackHeart.svg
  src/pages/main/MainDetail.jsx
  src/pages/pr/PRDetail.jsx
  src/pages/pr/PREdit.jsx
Labels: enhancement, high
