Repository FRONTENDBOOTCAMP-11th/DAEDDA, pull requests merged in 2025-03, with the labels that each got.

#221 [FEAT] 지도 기능 추가
  index.html
  src/pages/main/post/BasicMap.jsx
  src/pages/main/post/PostDetail.jsx
  src/pages/main/post/PostEdit.jsx
  src/pages/main/post/PostWrite.jsx
  src/pages/main/post/useKakaoLoader.jsx
  src/utills/useKakaoLoader.js
Labels: refactoring

#223 [REFACTOR] 위치 기반 구인 글 필터링 기능 구현
  src/hooks/useGetProducts.js
  src/pages/main/PostList.jsx
Labels: enhancement, medium, refactoring

#226 [Refactor] 홈 페이지 구인 글 리스트 무한 스크롤
  src/hooks/useGetProducts.js
  src/pages/main/ListItem.jsx
  src/pages/main/PostList.jsx
Labels: enhancement, refactoring

#230 [REFACTOR] 카카오 로그인 rest api .env 파일로 관리
  src/pages/user/SignIn.jsx
Labels: refactoring

#228 [REFACTOR] 홈 페이지 날짜 지난 구인글 마감 처리
  src/hooks/useGetProducts.js
  src/pages/main/ListItem.jsx
  src/pages/main/PostList.jsx
Labels: enhancement, refactoring

#232 [REFACTOR] 주소 미입력 시 글 유효성 활성화 안되는 버그 수정
  src/pages/main/post/BasicMap.jsx
  src/pages/main/post/PostEdit.jsx
  src/pages/main/post/PostWrite.jsx
Labels: bug, refactoring

#236 [Refactor] lazy loading 적용
  eslint.config.js
  routes.jsx
Labels: refactoring
