Repository FRONTENDBOOTCAMP-11th/DAEDDA, pull requests merged in 2025-02, with the labels that each got.

#199 ♻️ refactor: 같은ui 하나의 파일로 코드정리
  src/pages/myPage/MyBossReviewListItem.jsx
  src/pages/myPage/MyReviewListItem.jsx
  src/pages/myPage/MyReviews.jsx
  src/pages/myPage/Star.jsx
Labels: enhancement

#210 [REFACTOR] 리뷰 작성 시 product_id 전달
  src/pages/history/ReviewWrite.jsx
Labels: enhancement

#209 [REFACTOR] 프로필 이미지 삭제 기능 추가
  public/icons/x-box.svg
  src/pages/user/SignUp.jsx
Labels: enhancement, refactoring

#208 [REFACTOR] 조건부 버튼
  src/pages/user/SignUp.jsx
  src/pages/user/Terms.jsx
Labels: enhancement, refactoring

#211 UI개선 및 버그픽스 해결
  src/pages/main/PostList.jsx
  src/pages/myPage/MyReviewListItem.jsx
  src/pages/myPage/MyReviews.jsx
  src/pages/user/SignUp.jsx
Labels: refactoring

#215 [REFACTOR]Update README.md -ver2
  README.md
Labels: refactoring

#218 [REFACTOR] ui 수정
  public/icons/x-box.svg
  src/components/layout/Sidebar.jsx
  src/pages/myPage/Edit.jsx
  src/pages/user/Profile.jsx
  src/pages/user/SignUp.jsx
Labels: refactoring

#219 [REFACTOR]: 좋아요 목록 순서 변경 및 마감된 게시글 처리
  src/pages/myPage/LikeList.jsx
  src/pages/myPage/Likes.jsx
Labels: refactoring
