Repository FRONTENDBOOTCAMP-11th/DAEDDA, pull requests merged in 2025-01, with the labels that each got.

#82 [FEAT] InputField 컴포넌트와 함께 react-hook-form 사용
  src/components/layout/InputField.jsx
Labels: enhancement, high

#76 [FEAT] 약관 페이지 완성
  src/pages/user/Terms.jsx
Labels: enhancement, high

#88 [FEAT] 초기 splash 화면 완성
  src/App.jsx
Labels: enhancement, high

#96 [FEAT] Main 페이지 구인 글 리스트 보여주기
  src/pages/main/ListItem.jsx
  src/pages/main/MainList.jsx
  src/utills/func.js
Labels: enhancement, high

#90 [FEAT]내가 받은 리뷰 페이지 화면 뿌리는 작업
  src/pages/myPage/MyReviewList.jsx
  src/pages/myPage/MyReviews.jsx
Labels: enhancement, high

#93 [FEAT] 이메일 로그인 구현
  src/pages/user/SignIn.jsx
  src/zustand/userStore.js
Labels: enhancement, high

#97 [FEAT] 회원 정보 수정 기능
  public/icons/logout.svg
  public/icons/withdraw.svg
  src/pages/myPage/Edit.jsx
  src/pages/myPage/MyPage.jsx
Labels: enhancement, high

#107 [FEAT] error페이지 완성, myPage 적용
  public/images/404_daeddamon.png
  routes.jsx
  src/components/layout/Header.jsx
  src/pages/Error.jsx
  src/pages/myPage/MyPage.jsx
Labels: enhancement, high

#108 [FEAT] main 상세 수정 페이지
  src/pages/main/MainDetail.jsx
  src/pages/main/MainEdit.jsx
  src/pages/main/MainItem.jsx
  vite.config.js
Labels: enhancement

#114 [FEAT]myPage와 관련된 페이지 모두 zustand로 수정(프로필 제외)
  src/pages/Error.jsx
  src/pages/myPage/Edit.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyReviewList.jsx
  src/pages/myPage/MyReviews.jsx
Labels: enhancement, high

#117 [FEAT] 관심 리스트 페이지 구현
  src/index.css
  src/pages/myPage/LikeList.jsx
  src/pages/myPage/Likes.jsx
Labels: enhancement, high

#115 [FEAT] 프로필 페이지
  src/pages/myPage/LikeList.jsx
  src/pages/user/Profile.jsx
Labels: enhancement, high

#119 [FEAT] 회원가입 기능 완료
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
Labels: enhancement, high

#125 [FEAT] 글쓰기 API 변경, 찜하기 기능 추가, 버튼 비활성화, 이미지 업로드, 더미 데이터 제거
  src/pages/main/MainDetail.jsx
  src/pages/main/MainItem.jsx
  src/pages/main/MainWrite.jsx
Labels: bug, enhancement

#130 [FEAT] 카카오 로그인 구현
  src/pages/main/MainDetail.jsx
  src/pages/main/MainItem.jsx
  src/pages/myPage/Edit.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyReviewList.jsx
  src/pages/user/Profile.jsx
  src/pages/user/SignIn.jsx
Labels: enhancement, high

#129 [FEAT] 알바 내역 페이지, 리뷰 작성 페이지 구현
  package-lock.json
  package.json
  routes.jsx
  src/components/Button.jsx
  src/components/InputField.jsx
  src/components/layout/Footer.jsx
  src/hooks/useGetDetailedProduct.js
  src/hooks/useGetMyBookmark.js
  src/hooks/useGetOrder.js
  src/hooks/useGetOrderState.js
  src/hooks/useGetOrders.js
  src/hooks/useGetProducts.js
  src/hooks/useGetUser.js
  src/pages/Error.jsx
  src/pages/history/Employed.jsx
  src/pages/history/EmployedItem.jsx
  src/pages/history/Layout.jsx
  src/pages/history/ReviewWrite.jsx
  src/pages/history/Worked.jsx
  src/pages/history/WorkedItem.jsx
  src/pages/main/MainDetail.jsx
  src/pages/main/MainEdit.jsx
  src/pages/main/MainItem.jsx
  src/pages/main/MainWrite.jsx
  src/pages/myPage/Edit.jsx
  src/pages/myPage/MyReviewList.jsx
  src/pages/pr/PRDetail.jsx
  src/pages/pr/PREdit.jsx
  src/pages/pr/PRWrite.jsx
  src/pages/reviews/Hired.jsx
  src/pages/reviews/MyPerson.jsx
  src/pages/reviews/MyPlace.jsx
  src/pages/reviews/ReviewWrite.jsx
  src/pages/reviews/Worked.jsx
  src/pages/user/SignIn.jsx
  src/pages/user/SignUp.jsx
  src/pages/user/Terms.jsx
Labels: enhancement, high

#134 [BUG] 내가 시킨 일에서 리뷰 작성하기 시 axios 에러 발생
  src/hooks/useGetMyBookmark.js
  src/pages/history/Employed.jsx
  src/pages/history/EmployedItem.jsx
  src/pages/history/ReviewWrite.jsx
Labels: bug, medium

#136 [FEAT] 대타력 적용
  api/bruno-sample/dda/01.회원/01 회원가입,로그인/판매 회원 로그인(_id=2).bru
  api/bruno-sample/dda/01.회원/02.회원 정보 수정/회원 정보 수정(단일 속성, phone).bru
  api/bruno-sample/dda/01.회원/02.회원 정보 수정/회원 정보 수정(여러 속성, phone, name).bru
  api/bruno-sample/dda/01.회원/04.회원 정보 조회/지정한 회원 정보 조회(북마크 목록).bru
  api/bruno-sample/dda/02.일반 회원/03.구매 후기/판매자 후기 목록 조회.bru
  api/bruno-sample/dda/02.일반 회원/03.구매 후기/후기 등록.bru
  api/bruno-sample/dda/02.일반 회원/03.구매 후기/후기 상세 조회.bru
  api/bruno-sample/dda/02.일반 회원/05.북마크(찜하기)/내 북마크 한건 조회(상품).bru
  api/bruno-sample/dda/02.일반 회원/05.북마크(찜하기)/북마크 추가(사용자).bru
  api/bruno-sample/dda/02.일반 회원/05.북마크(찜하기)/북마크 추가(상품).bru
  api/bruno-sample/dda/06.시스템/01.파일/파일 업로드.bru
  src/pages/myPage/LikeList.jsx
  src/pages/myPage/Likes.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyReviewList.jsx
  src/pages/myPage/MyReviews.jsx
  src/pages/user/Profile.jsx
Labels: enhancement, high

#138 [FEAT] 카카오 회원 신규/기존 처리
  routes.jsx
  src/components/layout/Header.jsx
  src/pages/myPage/Edit.jsx
  src/pages/user/KakaoSignIn.jsx
  src/pages/user/SignIn.jsx
Labels: enhancement, high

#137 [FEAT] 메인 리스트 페이지 반응형 레이아웃 수정
  src/pages/main/ListItem.jsx
  src/pages/main/MainList.jsx
Labels: enhancement, medium

#141 [FEAT] 알바내역 페이지 상태 필터링
  api/bruno-sample/dda/01.회원/01 회원가입,로그인/판매 회원 로그인(_id=2).bru
  src/hooks/useGetOrderState.js
  src/hooks/useGetOrders.js
  src/hooks/useGetProducts.js
  src/pages/history/Employed.jsx
  src/pages/history/EmployedItem.jsx
  src/pages/history/State.jsx
  src/pages/history/Worked.jsx
  src/pages/history/WorkedItem.jsx
Labels: enhancement, high

#145 [FEAT]-대타력 별점 표시 및 리팩토링
  src/hooks/useProfileData.js
  src/pages/myPage/LikeList.jsx
  src/pages/myPage/Likes.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyReviewList.jsx
  src/pages/myPage/MyReviews.jsx
  src/pages/myPage/Star.jsx
  src/pages/user/Profile.jsx
  src/utills/calculateStarPower.js
Labels: enhancement, high

#148 [FEAT] 토큰 처리
  src/hooks/useAxiosInstance.js
  src/pages/user/SignIn.jsx
Labels: enhancement, high

#146 [FEAT] 메인 페이지 검색
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/hooks/useGetMyProducts.js
  src/hooks/useGetProducts.js
  src/pages/history/Employed.jsx
  src/pages/history/ReviewWrite.jsx
  src/pages/main/MainList.jsx
Labels: enhancement, high

#152 [FEAT] 로그인 페이지 코드 리팩토링
  src/pages/user/SignIn.jsx
Labels: enhancement

#157 [FEAT] terms 페이지 폰트 수정
  src/pages/user/Terms.jsx
Labels: enhancement, medium

#159 [BUG] 로그인 안했을 때 로그인 페이지로 이동오류 수정
  src/components/layout/index.jsx
  src/hooks/useProfileData.js
  src/pages/myPage/Likes.jsx
  src/pages/myPage/MyPage.jsx
Labels: enhancement, high

#162 메인, 알바내역, 리뷰 작성 페이지 폰트사이즈 rem으로 수정
  src/pages/history/ReviewWrite.jsx
  src/pages/main/ListItem.jsx
  src/pages/main/MainList.jsx
Labels: enhancement, medium

#168 [FEAT] main 폴더 파일 정리
  routes.jsx
  src/pages/main/post/Badge.jsx
  src/pages/main/post/MainMap.jsx
  src/pages/main/post/PRWrite.jsx
  src/pages/main/post/PostDetail.jsx
  src/pages/main/post/PostEdit.jsx
  src/pages/main/post/PostPR.jsx
  src/pages/main/post/PostWrite.jsx
  src/pages/main/post/useKakaoLoader.jsx
Labels: enhancement

#161 [FEAT] 메인 페이지 필터링 적용
  src/hooks/useGetProducts.js
  src/pages/main/PostList.jsx
Labels: enhancement, medium

#170 [FEAT] 사이드바 구현
  src/App.jsx
  src/components/layout/Header.jsx
  src/components/layout/Sidebar.jsx
  src/components/layout/index.jsx
  src/index.css
  src/zustand/sidebarStore.js
Labels: enhancement, medium

#171 [FEAT] 알림 기능 구현
  public/icons/redAlarm.svg
  routes.jsx
  src/components/layout/Header.jsx
  src/hooks/useAddAlarm.js
  src/hooks/useEditProductState.js
  src/hooks/useGetDetailedProduct.js
  src/pages/alarm/Alarm.jsx
  src/pages/alarm/AlarmItem.jsx
  src/pages/history/EmployedItem.jsx
  src/pages/history/ReviewWrite.jsx
  src/pages/main/post/PRWrite.jsx
  src/pages/main/post/PostPR.jsx
  src/zustand/alarmExistStore.js
Labels: enhancement

#177 [FEAT]- 폰트 rem수정 및 알바력 뱃지 뿌리기
  routes.jsx
  src/components/layout/Header.jsx
  src/components/layout/Sidebar.jsx
  src/pages/Error.jsx
  src/pages/Refund.jsx
  src/pages/main/post/Badge.jsx
  src/pages/main/post/PostPR.jsx
  src/pages/myPage/MyReviews.jsx
  src/pages/user/Profile.jsx
Labels: enhancement, high

#178 [FEAT] 로그인이 필요한 페이지 ProtectedRoutes 로 막기
  ProtectedRoutes.jsx
  routes.jsx
Labels: enhancement, medium

#179 [BUG] 내가 시킨 일 송금하기 누른 후 데이터 refetch, 기타 버그 수정
  src/components/layout/Header.jsx
  src/hooks/useGetMyProducts.js
  src/hooks/useGetOrder.js
  src/pages/alarm/Alarm.jsx
  src/pages/history/Employed.jsx
  src/pages/history/EmployedItem.jsx
  src/pages/history/ReviewWrite.jsx
  src/pages/history/WorkedItem.jsx
  src/pages/main/PostList.jsx
  src/pages/main/post/PostDetail.jsx
  src/pages/main/post/PostEdit.jsx
Labels: bug, high

#180 [FEAT] 지도 API 추가
  package-lock.json
  package.json
  src/hooks/useAddAlarm.js
  src/hooks/useEditProductWorker.js
  src/pages/main/post/MainMap.jsx
  src/pages/main/post/PostDetail.jsx
  src/pages/main/post/PostEdit.jsx
  src/pages/main/post/PostPR.jsx
  src/pages/main/post/PostWrite.jsx
  src/pages/main/post/useKakaoLoader.jsx
Labels: enhancement

#185 [FEAT] 날짜 지난 구인 글 메인에 안 보이게 하기
  src/pages/main/PostList.jsx
Labels: enhancement

#190 [FEAT] 날짜에 따른 환불 수수료 적용, input 버그 수정
  src/pages/main/post/PostDetail.jsx
  src/pages/main/post/PostPR.jsx
  src/pages/main/post/PostWrite.jsx
Labels: enhancement

#193 [FEAT] 알바 내역 상세 보기에서 이동한 디테일 페이지에서 뒤로가기 클릭시 알바 내역으로
  src/components/layout/Header.jsx
  src/pages/history/EmployedItem.jsx
  src/pages/history/WorkedItem.jsx
  src/pages/main/post/PostDetail.jsx
Labels: enhancement
